[[edge_functions]]
  path = "/*"
  
  # name of the function in netlify/edge_functions
  function = "language-redirect"

[[plugins]]
  package = "@algolia/netlify-plugin-crawler"

  [plugins.inputs]
  branches = ['main']
  disabled = false
  pathPrefix = "/"
  renderJavaScript = true